New page styling
hlxsites/tlcgrp pull request #173
Opened 2023-07-03 11:57 UTC by 2016DigiTech

Fix #172 

Test URLs: https://new-page-styling--tlcgrp--hlxsites.hlx.page/experience-vouchers

- Before: https://main--tlcgrp--hlxsites.hlx.page/
- After: https://new-page-styling--tlcgrp--hlxsites.hlx.page/experience-vouchers

2023-07-12 12:25 UTC, 2016DigiTech commented
@vdua Please review

2023-07-14 08:28 UTC, 2016DigiTech commented
@vdua Please review

2023-07-17 05:31 UTC, 2016DigiTech commented
@asthabh23 @rofe Please view the #172

2023-07-17 05:49 UTC, asthabh23 requested changes
please consider fixing on the suggested changes, and prefer to not include changes not required for the PR.

2023-07-17 05:49 UTC, asthabh23 commented on blocks/cards/cards.css
> +  .review > ul > li .cards-card-body p:nth-child(3) {
you should prefer to use semantics rather than accessing p tags via position numbers

2023-07-17 05:49 UTC, asthabh23 commented on blocks/form/form.css
> +  color: #808080;
preferably use variable names rather than color codes directly.

2023-07-17 05:49 UTC, asthabh23 commented on blocks/form/form.css
I don't see changes related to form relevant for  this PR. can you point me to why these changes are required here?

2023-07-17 05:49 UTC, asthabh23 commented on blocks/form/form.js
I don't see changes related to form relevant for this PR. can you point me to why these changes are required here?

2023-07-17 05:49 UTC, asthabh23 commented on styles/styles.css
> +    color: #808080;
preferably use variable names

2023-07-17 05:49 UTC, asthabh23 commented on styles/styles.css
> +  main .carve-career-all-section .default-content-wrapper h3:nth-child(3) {
preferably use semantics (if required different headings) to distinguish on the changes required rather than making them fixed via numbers

2023-07-17 06:12 UTC, vdua commented on blocks/form/form.js
> +    ph.setAttribute('value', '');
These changes are already merged in main

https://github.com/hlxsites/tlcgrp/pull/171/files

2023-07-17 06:57 UTC, 2016DigiTech commented
@asthabh23 Please check

2023-07-17 09:12 UTC, asthabh23 commented on blocks/form/form.css
since this file change is not directly related to the styling of the page for which PR is raised, it would be great to create a separate PR for this mentioning the right URL for the form page

2023-07-18 05:20 UTC, 2016DigiTech commented
@asthabh23 @vdua Please approve

2023-07-18 05:50 UTC, asthabh23 approved these changes
@2016DigiTech  for further PRs, please make sure you include only changes specific to the page which is impacted by the particular changes

2023-07-19 11:48 UTC, merged